import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  var _categories = [
    'Accelerator Physics',
    'Adaptation and Self-Organizing Systems',
    'Algebraic Geometry',
    'Algebraic Topology',
    'Analysis of PDEs',
    'Applications',
    'Applied Physics',
    'Artificial Intelligence',
    'Astrophysics',
    'Astrophysics of Galaxies',
    'Atmospheric and Oceanic Physics',
    'Atomic Physics',
    'Atomic and Molecular Clusters',
    'Audio and Speech Processing',
    'Biological Physics',
    'Biomolecules',
    'Category Theory',
    'Cell Behavior',
    'Cellular Automata and Lattice Gases',
    'Chaotic Dynamics',
    'Chemical Physics',
    'Classical Analysis and ODEs',
    'Classical Physics',
    'Combinatorics',
    'Commutative Algebra',
    'Complex Variables',
    'Computation',
    'Computation and Language',
    'Computational Complexity',
    'Computational Engineering, Finance, and Science',
    'Computational Finance',
    'Computational Geometry',
    'Computational Physics',
    'Computer Science and Game Theory',
    'Computer Vision and Pattern Recognition',
    'Computers and Society',
    'Cosmology and Nongalactic Astrophysics',
    'Cryptography and Security',
    'Data Analysis, Statistics and Probability',
    'Data Structures and Algorithms',
    'Databases',
    'Differential Geometry',
    'Digital Libraries',
    'Discrete Mathematics',
    'Disordered Systems and Neural Networks',
    'Distributed, Parallel, and Cluster Computing',
    'Dynamical Systems',
    'Earth and Planetary Astrophysics',
    'Econometrics',
    'Economics',
    'Emerging Technologies',
    'Exactly Solvable and Integrable Systems',
    'Fluid Dynamics',
    'Formal Languages and Automata Theory',
    'Functional Analysis',
    'General Finance',
    'General Literature',
    'General Mathematics',
    'General Physics',
    'General Relativity and Quantum Cosmology',
    'General Topology',
    'Genomics',
    'Geometric Topology',
    'Geophysics',
    'Graphics',
    'Group Theory',
    'Hardware Architecture',
    'High Energy Astrophysical Phenomena',
    'High Energy Physics - Experiment',
    'High Energy Physics - Lattice',
    'High Energy Physics - Phenomenology',
    'High Energy Physics - Theory',
    'History and Overview',
    'History and Philosophy of Physics',
    'Human-Computer Interaction',
    'Image and Video Processing',
    'Information Retrieval',
    'Information Theory',
    'Instrumentation and Detectors',
    'Instrumentation and Methods for Astrophysics',
    'K-Theory and Homology',
    'Learning',
    'Logic',
    'Logic in Computer Science',
    'Machine Learning',
    'Materials Science',
    'Mathematical Finance',
    'Mathematical Physics',
    'Mathematical Software',
    'Medical Physics',
    'Mesoscale and Nanoscale Physics',
    'Methodology',
    'Metric Geometry',
    'Molecular Networks',
    'Multiagent Systems',
    'Multimedia',
    'Networking and Internet Architecture',
    'Neural and Evolutionary Computing',
    'Neurons and Cognition',
    'Nuclear Experiment',
    'Nuclear Theory',
    'Number Theory',
    'Numerical Analysis',
    'Operating Systems',
    'Operator Algebras',
    'Optics',
    'Optimization and Control',
    'Other Computer Science',
    'Other Condensed Matter',
    'Other Quantitative Biology',
    'Other Statistics',
    'Pattern Formation and Solitons',
    'Performance',
    'Physics Education',
    'Physics and Society',
    'Plasma Physics',
    'Popular Physics',
    'Populations and Evolution',
    'Portfolio Management',
    'Pricing of Securities',
    'Probability',
    'Programming Languages',
    'Quantitative Methods',
    'Quantum Algebra',
    'Quantum Gases',
    'Quantum Physics',
    'Representation Theory',
    'Rings and Algebras',
    'Risk Management',
    'Robotics',
    'Signal Processing',
    'Social and Information Networks',
    'Soft Condensed Matter',
    'Software Engineering',
    'Solar and Stellar Astrophysics',
    'Sound',
    'Space Physics',
    'Spectral Theory',
    'Statistical Finance',
    'Statistical Mechanics',
    'Statistics Theory',
    'Strongly Correlated Electrons',
    'Subcellular Processes',
    'Superconductivity',
    'Symbolic Computation',
    'Symplectic Geometry',
    'Systems and Control',
    'Tissues and Organs',
    'Trading and Market Microstructure'
  ];
  int _categoriesIndex = 0;
  var rng = new Random();
  void _categoriesIncrement() {
    _categoriesIndex = rng.nextInt(_categories.length);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          backgroundColor: Colors.white,
          elevation: 0.0,
          title: Text(
            "Arxiv Reader",
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.redAccent, fontSize: 25),
          ),
          centerTitle: true,
          leading: IconButton(
            // padding: EdgeInsets.only(left: 20.0),
            icon: Icon(Icons.arrow_back_ios_sharp),
            onPressed: () => print("menu"),
            iconSize: 20,
            color: Colors.black,
          ),
          actions: [
            IconButton(
              // padding: EdgeInsets.only(right: 25.0),
              icon: Icon(Icons.search_sharp),
              onPressed: () => print("search"),
              iconSize: 30,
              color: Colors.black,
            )
          ],
        ),
        body: Center(
          child: AnimatedOpacity(
            duration: Duration(milliseconds: 100),
            opacity: 1.0,
            child: Text(
              _categories[_categoriesIndex],
              style: TextStyle(
                  fontSize: 20, fontWeight: FontWeight.bold, color: Colors.red),
            ),
          ),
          heightFactor: 25,
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: _categoriesIncrement,
          child: Icon(Icons.flip),
        ),
      ),
    );
  }
}
